import{backend}from'../lib/backend';import React,{useMemo,useState}from'react';
import{Edit3,SlidersHorizontal,Search,Eye}from'lucide-react';
import{useApp}from'../context/AppContext';
import{Badge,Card,PageHead,money}from'../components/UI';
export default function Inventory(){
 const{products=[],profile,updateInventoryItem,adjustInventory,reload}=useApp();
 const[q,setQ]=useState(''),[edit,setEdit]=useState(null),[adjust,setAdjust]=useState(null);
 const role=profile?.role;const canEdit=['Developer','Admin','Manager'].includes(role);const canAdjust=['Developer','Admin'].includes(role);const canSeeCost=['Developer','Admin','Manager'].includes(role);
 const rows=useMemo(()=>products.filter(p=>`${p.name} ${p.sku||''} ${p.category||''}`.toLowerCase().includes(q.toLowerCase())),[products,q]);
 const save=async()=>{try{await updateInventoryItem(edit);await backend.savePartRate(edit.id,edit.technician_percentage);await reload();setEdit(null)}catch(e){alert(e.message)}};
 const doAdjust=async()=>{const reason=prompt('Reason for stock adjustment:');if(!reason)return;try{await adjustInventory(adjust.id,Number(adjust.change),reason);setAdjust(null)}catch(e){alert(e.message)}};
 return <><PageHead title="Inventory" subtitle={canEdit?'Phones, accessories and repair parts with stock controls.':'Read-only stock availability for your work.'}/>
 {!canEdit&&<div className="success-banner"><Eye/><div><b>Read-only inventory</b><span>You can check available stock, but you cannot edit items, cost or quantities.</span></div></div>}
 <div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search phones, accessories or repair parts..."/></div></div>
 <Card className="table-card"><table><thead><tr><th>Item</th><th>Category</th><th>Stock</th><th>Low Limit</th>{canSeeCost&&<th>Cost</th>}<th>Status</th>{canEdit&&<th>Actions</th>}</tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.sku||'No SKU'}</small></td><td>{p.category}</td><td><strong>{p.qty}</strong></td><td>{p.low}</td>{canSeeCost&&<td>{money(p.cost)}</td>}<td><Badge tone={p.qty<=p.low?'low':'healthy'}>{p.qty<=p.low?'Low Stock':'Healthy'}</Badge></td>{canEdit&&<td><div className="row-actions"><button className="btn ghost sm" onClick={()=>setEdit({...p})}><Edit3 size={15}/>Edit</button>{canAdjust&&<button className="btn ghost sm" onClick={()=>setAdjust({id:p.id,name:p.name,change:0})}><SlidersHorizontal size={15}/>Adjust</button>}</div></td>}</tr>)}{!rows.length&&<tr><td colSpan={canEdit?7:5}><div className="empty-inline">No inventory items found.</div></td></tr>}</tbody></table></Card>
 {canEdit&&edit&&<div className="modal-backdrop"><Card className="modal-card"><h3>Edit Inventory Item</h3><div className="formgrid"><label>Name<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>SKU<input value={edit.sku||''} onChange={e=>setEdit({...edit,sku:e.target.value})}/></label><label>Category<select value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}>{[...new Set(['Phones','Accessories','Repair Parts',...products.map(p=>p.category)])].map(c=><option key={c}>{c}</option>)}</select></label><label>Low stock limit<input type="number" min="0" value={edit.low} onChange={e=>setEdit({...edit,low:e.target.value})}/></label><label>Technician share of part profit (%)<input type="number" min="0" max="100" step="0.01" placeholder="Use technician default" value={edit.technician_percentage??''} onChange={e=>setEdit({...edit,technician_percentage:e.target.value})}/></label><label className="checkline"><input type="checkbox" checked={edit.active!==false} onChange={e=>setEdit({...edit,active:e.target.checked})}/>Active item</label></div><div className="split-actions"><button className="btn ghost" onClick={()=>setEdit(null)}>Cancel</button><button className="btn primary" onClick={save}>Save Changes</button></div></Card></div>}
 {canAdjust&&adjust&&<div className="modal-backdrop"><Card className="modal-card"><h3>Adjust Stock · {adjust.name}</h3><p>Positive adds stock; negative reduces stock. A reason is required.</p><label>Quantity change<input type="number" value={adjust.change} onChange={e=>setAdjust({...adjust,change:e.target.value})}/></label><div className="split-actions"><button className="btn ghost" onClick={()=>setAdjust(null)}>Cancel</button><button className="btn primary" onClick={doAdjust}>Apply Adjustment</button></div></Card></div>}</>;
}
