import React,{useMemo,useState}from'react';
import{ShoppingCart,Trash2,PauseCircle,PlayCircle,Printer,RotateCcw,XCircle,Plus,Minus}from'lucide-react';
import{useApp}from'../context/AppContext';import{Badge,Card,PageHead,money}from'../components/UI';
export default function POS(){
 const{products,sales,profile,createPendingSale,completePendingSale,cancelSale,reverseSale}=useApp();
 const[cart,setCart]=useState([]),[productId,setProductId]=useState(''),[price,setPrice]=useState(''),[tab,setTab]=useState('new'),[busy,setBusy]=useState(false);
 const product=products.find(x=>x.id===productId);const role=profile?.role;const canCancel=['Developer','Admin','Manager'].includes(role);const canReverse=['Developer','Admin'].includes(role);
 const pending=sales.filter(s=>s.status==='Pending');const completed=sales.filter(s=>s.status!=='Pending');const total=useMemo(()=>cart.reduce((s,x)=>s+x.qty*x.price,0),[cart]);
 const add=()=>{if(!product)return;if(Number(price)<product.cost)return alert(`Selling price cannot be below ${money(product.cost)}`);if(product.qty<1)return alert('Out of stock');setCart(c=>{const old=c.find(x=>x.productId===product.id);return old?c.map(x=>x.productId===product.id?{...x,qty:Math.min(x.qty+1,product.qty)}:x):[...c,{productId:product.id,name:product.name,qty:1,price:Number(price),cost:product.cost,stock:product.qty}]});setProductId('');setPrice('')};
 const hold=async()=>{if(!cart.length)return alert('Cart is empty');try{setBusy(true);await createPendingSale({items:cart.map(x=>({product_id:x.productId,qty:x.qty,sale_price:x.price}))});setCart([]);setTab('pending')}catch(e){alert(e.message)}finally{setBusy(false)}};
 const checkout=async()=>{if(!cart.length)return alert('Cart is empty');try{setBusy(true);const held=await createPendingSale({items:cart.map(x=>({product_id:x.productId,qty:x.qty,sale_price:x.price}))});await completePendingSale(held.sale_id,total,'Cash');setCart([]);alert('Sale completed successfully.')}catch(e){alert(e.message)}finally{setBusy(false)}};
 const completeHeld=async s=>{try{await completePendingSale(s.dbId,s.total,'Cash');alert('Pending order completed.')}catch(e){alert(e.message)}};
 const cancel=async s=>{const reason=prompt('Cancellation reason:');if(!reason)return;try{await cancelSale(s.dbId,reason)}catch(e){alert(e.message)}};
 const reverse=async s=>{const reason=prompt('Reason for reversing this paid order:');if(!reason)return;try{await reverseSale(s.dbId,reason);alert('Sale reversed and stock restored.')}catch(e){alert(e.message)}};
 return <><PageHead title="Point of Sale" subtitle="Professional checkout, held orders, cancellation and controlled reversals."/>
 <div className="pos-tabs"><button className={tab==='new'?'active':''} onClick={()=>setTab('new')}>New Sale</button><button className={tab==='pending'?'active':''} onClick={()=>setTab('pending')}>Pending Orders <Badge>{pending.length}</Badge></button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>Order History</button></div>
 {tab==='new'&&<div className="pos-layout"><Card><h3>Add Product</h3><label>Product<select value={productId} onChange={e=>{setProductId(e.target.value);setPrice('')}}><option value="">Select product</option>{products.filter(x=>x.active!==false&&x.qty>0).map(x=><option key={x.id} value={x.id}>{x.name} — {x.qty} in stock</option>)}</select></label>{product&&<div className="pos-product-info"><span>Cost floor <b>{money(product.cost)}</b></span><span>Available <b>{product.qty}</b></span></div>}<label>Negotiated selling price<input type="number" min={product?.cost||0} value={price} onChange={e=>setPrice(e.target.value)} placeholder="PKR"/></label><button className="btn primary full" onClick={add}><ShoppingCart size={17}/>Add to Cart</button></Card>
 <Card><div className="section-title"><div><h3>Current Order</h3><p>{cart.length} line item(s)</p></div><strong>{money(total)}</strong></div>{!cart.length?<div className="empty-inline">Cart is empty.</div>:cart.map(x=><div className="cart-row" key={x.productId}><div><b>{x.name}</b><small>{money(x.price)} each</small></div><div className="qty-control"><button onClick={()=>setCart(c=>c.map(i=>i.productId===x.productId?{...i,qty:Math.max(1,i.qty-1)}:i))}><Minus size={14}/></button><b>{x.qty}</b><button onClick={()=>setCart(c=>c.map(i=>i.productId===x.productId?{...i,qty:Math.min(i.stock,i.qty+1)}:i))}><Plus size={14}/></button></div><strong>{money(x.qty*x.price)}</strong><button className="iconbtn danger" onClick={()=>setCart(c=>c.filter(i=>i.productId!==x.productId))}><Trash2 size={16}/></button></div>)}<div className="pos-total"><span>Total</span><strong>{money(total)}</strong></div><div className="split-actions"><button className="btn ghost" disabled={busy||!cart.length} onClick={hold}><PauseCircle size={17}/>Hold Order</button><button className="btn primary" disabled={busy||!cart.length} onClick={checkout}><Printer size={17}/>Pay & Print</button></div></Card></div>}
 {tab==='pending'&&<OrderTable rows={pending} pending canCancel={canCancel} onComplete={completeHeld} onCancel={cancel}/>} {tab==='history'&&<OrderTable rows={completed} canReverse={canReverse} onReverse={reverse}/>}</>}
function OrderTable({rows,pending,canCancel,canReverse,onComplete,onCancel,onReverse}){return <Card className="table-card"><table><thead><tr><th>Invoice</th><th>Date</th><th>Cashier</th><th>Items</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(s=><tr key={s.dbId}><td><b>{s.id}</b></td><td>{s.date}</td><td>{s.cashier||'—'}</td><td>{s.items?.map(i=>`${i.name} ×${i.qty}`).join(', ')||'—'}</td><td><strong>{money(s.total)}</strong></td><td><Badge>{s.status}</Badge></td><td><div className="row-actions">{pending&&<button className="btn primary sm" onClick={()=>onComplete(s)}><PlayCircle size={15}/>Resume & Pay</button>}{pending&&canCancel&&<button className="btn danger sm" onClick={()=>onCancel(s)}><XCircle size={15}/>Cancel</button>}{!pending&&canReverse&&['Paid','Partially Paid','Unpaid'].includes(s.status)&&<button className="btn danger sm" onClick={()=>onReverse(s)}><RotateCcw size={15}/>Reverse</button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan="7"><div className="empty-inline">No orders found.</div></td></tr>}</tbody></table></Card>}
