import React,{useEffect,useState}from'react';import{Bell,Printer,Save,Settings2,Store,Wrench,ShieldCheck}from'lucide-react';import{useApp}from'../context/AppContext';import{Card,PageHead}from'../components/UI';
const defaults={shop:{name:'Mobile Shop',phone:'',address:'',receiptFooter:'Thank you for your business'},printing:{paperWidth:'80mm',leftMargin:2,rightMargin:2,autoPrint:true},business:{blockBelowCost:true,lowStockNotifications:true,lowFeedbackAlerts:true,repairDeadlineAlerts:true},repairs:{defaultWarrantyDays:7,defaultTechnicianRate:50}};
export default function Settings(){const{settings,saveSetting,profile}=useApp();const[f,setF]=useState(defaults),[saving,setSaving]=useState('');useEffect(()=>setF({...defaults,...settings,shop:{...defaults.shop,...settings.shop},printing:{...defaults.printing,...settings.printing},business:{...defaults.business,...settings.business},repairs:{...defaults.repairs,...settings.repairs}}),[settings]);const save=async key=>{try{setSaving(key);await saveSetting(key,f[key]);alert('Settings saved.')}catch(e){alert(e.message)}finally{setSaving('')}};return <><PageHead title="Settings" subtitle="Real persistent shop, POS, printing, notification and repair controls."/><div className="settings-grid-pro"><SettingCard icon={Store} title="Shop Profile" onSave={()=>save('shop')} saving={saving==='shop'}><label>Shop name<input value={f.shop.name} onChange={e=>setF({...f,shop:{...f.shop,name:e.target.value}})}/></label><label>Phone<input value={f.shop.phone} onChange={e=>setF({...f,shop:{...f.shop,phone:e.target.value}})}/></label><label>Address<textarea value={f.shop.address} onChange={e=>setF({...f,shop:{...f.shop,address:e.target.value}})}/></label><label>Receipt footer<input value={f.shop.receiptFooter} onChange={e=>setF({...f,shop:{...f.shop,receiptFooter:e.target.value}})}/></label></SettingCard>
<SettingCard icon={Printer} title="Thermal Printing" onSave={()=>save('printing')} saving={saving==='printing'}><label>Paper width<select value={f.printing.paperWidth} onChange={e=>setF({...f,printing:{...f.printing,paperWidth:e.target.value}})}><option>80mm</option><option>58mm</option></select></label><div className="formgrid"><label>Left margin<input type="number" value={f.printing.leftMargin} onChange={e=>setF({...f,printing:{...f.printing,leftMargin:Number(e.target.value)}})}/></label><label>Right margin<input type="number" value={f.printing.rightMargin} onChange={e=>setF({...f,printing:{...f.printing,rightMargin:Number(e.target.value)}})}/></label></div><Check label="Auto print after completed sale" checked={f.printing.autoPrint} onChange={v=>setF({...f,printing:{...f.printing,autoPrint:v}})}/></SettingCard>
<SettingCard icon={Bell} title="Business Notifications" onSave={()=>save('business')} saving={saving==='business'}><Check label="Block selling below cost" checked={f.business.blockBelowCost} onChange={v=>setF({...f,business:{...f.business,blockBelowCost:v}})}/><Check label="Low stock notifications" checked={f.business.lowStockNotifications} onChange={v=>setF({...f,business:{...f.business,lowStockNotifications:v}})}/><Check label="Low feedback alerts (1–2 stars)" checked={f.business.lowFeedbackAlerts} onChange={v=>setF({...f,business:{...f.business,lowFeedbackAlerts:v}})}/><Check label="Repair deadline alerts" checked={f.business.repairDeadlineAlerts} onChange={v=>setF({...f,business:{...f.business,repairDeadlineAlerts:v}})}/></SettingCard>
<SettingCard icon={Wrench} title="Repair Defaults" onSave={()=>save('repairs')} saving={saving==='repairs'}><label>Default warranty days<input type="number" min="0" value={f.repairs.defaultWarrantyDays} onChange={e=>setF({...f,repairs:{...f.repairs,defaultWarrantyDays:Number(e.target.value)}})}/></label><label>Default technician share %<input type="number" min="0" max="100" value={f.repairs.defaultTechnicianRate} onChange={e=>setF({...f,repairs:{...f.repairs,defaultTechnicianRate:Number(e.target.value)}})}/></label></SettingCard>
<Card><ShieldCheck/><h3>Security</h3><p>Signed in as <b>{profile?.full_name}</b> · {profile?.role}. Sensitive stock, reversal and user actions are enforced by secure Supabase functions and RLS.</p></Card></div></>}
function Check({label,checked,onChange}){return <label className="switch-row"><span>{label}</span><input type="checkbox" checked={!!checked} onChange={e=>onChange(e.target.checked)}/></label>}
function SettingCard({icon:Icon,title,children,onSave,saving}){return <Card><div className="section-title"><div><Icon size={20}/><h3>{title}</h3></div></div>{children}<button className="btn primary" onClick={onSave} disabled={saving}><Save size={16}/>{saving?'Saving...':'Save Settings'}</button></Card>}
