import React,{useMemo,useState}from'react';
import{Link,useSearchParams}from'react-router-dom';import{ArrowLeft,ArrowUpRight,CalendarDays,CheckCircle2,History,Plus,Search,WalletCards,X}from'lucide-react';
import{useApp}from'../context/AppContext';import{backend}from'../lib/backend';import{Badge,Card,PageHead,Stat,money}from'../components/UI';
const amount=v=>Number(v||0);
const signed=e=>['payment','deduction','reversal'].includes(e.entry_type)?-amount(e.amount):amount(e.amount);
const date=v=>v?new Date(v).toLocaleString(): '—';
const day=v=>{if(!v)return '';const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export default function TechnicianLedger(){
 const{techs=[],repairs=[],ledger=[],profile,reload}=useApp();const[searchParams,setSearchParams]=useSearchParams();const selectedId=searchParams.get('technician')||'';const setSelectedId=id=>setSearchParams(id?{technician:id}:{});const[dialog,setDialog]=useState(null),[value,setValue]=useState(''),[reason,setReason]=useState(''),[method,setMethod]=useState('Cash'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[view,setView]=useState('repairs');
 const allowed=['Admin','Manager','Developer'].includes(profile?.role);const selected=techs.find(t=>t.id===selectedId);const entries=ledger.filter(e=>e.technician_id===selectedId);
 const stats=useMemo(()=>({earned:entries.filter(e=>e.entry_type!=='payment').reduce((s,e)=>s+signed(e),0),paid:entries.filter(e=>e.entry_type==='payment').reduce((s,e)=>s+amount(e.amount),0)}),[entries]);
 const earningFor=id=>entries.filter(e=>e.repair_id===id&&e.entry_type!=='payment').reduce((s,e)=>s+signed(e),0);
 const matchesDate=v=>(!from||day(v)>=from)&&(!to||day(v)<=to);
 const rows=repairs.filter(r=>r.technicianId===selectedId&&matchesDate(r.completedRaw||r.createdRaw)&&`${r.id} ${r.customer} ${r.phone}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>new Date(b.completedRaw||b.createdRaw)-new Date(a.completedRaw||a.createdRaw));
 const transactions=entries.filter(e=>matchesDate(e.created_at)&&`${e.description||''} ${e.entry_type}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));
 const open=(type,tech,repair=null)=>{setDialog({type,techId:tech.id,repair});setValue(type==='settlement'?String(Math.max(0,tech.balance)):type==='adjust'?String(earningFor(repair.dbId)):'');setReason('');setMethod('Cash');setError('')};
 const currentTech=techs.find(t=>t.id===dialog?.techId);const remaining=amount(currentTech?.balance)-amount(value);
 const save=async e=>{e.preventDefault();if(busy)return;const numeric=Number(value);if(value===''||!Number.isFinite(numeric)||numeric<0||(dialog.type!=='adjust'&&numeric<=0)){setError('Enter a valid amount.');return}if(dialog.type==='settlement'&&numeric>amount(currentTech?.balance)){setError('Payment cannot exceed the current payable balance.');return}if(!reason.trim()){setError('Enter a reason or payment reference.');return}try{setBusy(true);setError('');let result;if(dialog.type==='settlement')result=await backend.settleTechnician(dialog.techId,numeric,method,reason.trim());else if(dialog.type==='adjust')await backend.setRepairEarning(dialog.repair.dbId,numeric,reason.trim());else await backend.adjustTechnician(dialog.techId,'bonus',numeric,reason.trim());await reload();setMessage(dialog.type==='settlement'?`${currentTech.name}: ${money(result.paid)} paid. ${money(result.remaining)} remaining.`:dialog.type==='adjust'?`${dialog.repair.id}: technician earning updated to ${money(numeric)}.`:`Manual earning of ${money(numeric)} added for ${currentTech.name}.`);setDialog(null)}catch(e){setError(e.message||String(e))}finally{setBusy(false)}};
 const actions=selected?<><button className="btn ghost" onClick={()=>{setSelectedId('');setQuery('');setFrom('');setTo('')}}><ArrowLeft size={16}/>All Technicians</button>{allowed&&<><button className="btn ghost" onClick={()=>open('manual',selected)}><Plus size={16}/>Manual Earning</button><button className="btn primary" disabled={selected.balance<=0} onClick={()=>open('settlement',selected)}><WalletCards size={16}/>Settlement</button></>}</>:null;
 return <><PageHead title={selected?`${selected.name} · Ledger Details`:'Technician Ledger'} subtitle={selected?'Repair earnings, payments and a complete adjustment history.':'Track each technician’s earnings and settle any portion of the payable balance.'} actions={actions}/>{message&&<div className="success-banner" role="status"><CheckCircle2 size={18}/>{message}</div>}
 {!selected?<><div className="stats ledger-overview"><Stat label="Total Payable" value={money(techs.reduce((s,t)=>s+Math.max(0,t.balance),0))} note="Across all technicians" icon={WalletCards}/><Stat label="Technicians" value={techs.length} note="Staff with technician accounts" icon={History}/></div><div className="tech-ledgers">{techs.map(t=><Card key={t.id} className="technician-card"><div className="personrow"><div className="avatar">{t.name.split(' ').map(w=>w[0]).join('').slice(0,2)}</div><div><h3>{t.name}</h3><span>{t.rate}% default share · {t.completed} completed</span></div><Badge>{t.status}</Badge></div><div className="big-balance"><span>{t.balance<0?'Overpaid credit':'Current Payable'}</span><strong>{money(Math.abs(t.balance))}</strong></div><div className="split"><span>Active repairs <b>{t.active}</b></span><span>Completed <b>{t.completed}</b></span></div><div className="ledger-card-actions"><button className="btn ghost" onClick={()=>{setSelectedId(t.id);setQuery('')}}><History size={16}/>Details</button>{allowed&&<button className="btn primary" disabled={t.balance<=0} onClick={()=>open('settlement',t)}><WalletCards size={16}/>Settlement</button>}</div></Card>)}{!techs.length&&<Card className="empty"><WalletCards size={32}/><h3>No technician accounts yet</h3><p>Add a technician under Users & Roles to begin tracking earnings.</p></Card>}</div></>:<><div className="stats ledger-stats"><Stat label="Total Earnings" value={money(stats.earned)} note="After manual adjustments" icon={ArrowUpRight}/><Stat label="Total Settled" value={money(stats.paid)} note="Recorded technician payments" icon={CheckCircle2}/><Stat label={selected.balance<0?'Overpaid Credit':'Current Payable'} value={money(Math.abs(selected.balance))} note={selected.balance<0?'Offsets future earnings':'Earnings less settlements'} icon={WalletCards}/></div><Card className="ledger-toolbar"><div className="seg"><button className={view==='repairs'?'active':''} onClick={()=>setView('repairs')}>Repair Earnings</button><button className={view==='activity'?'active':''} onClick={()=>setView('activity')}>Payments & Adjustments</button></div><div className="toolbar ledger-filters"><div className="search"><Search size={17}/><input aria-label="Search ledger" value={query} onChange={e=>setQuery(e.target.value)} placeholder={view==='repairs'?'Search job, customer or device':'Search transaction or note'}/></div><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" min={from||undefined} value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn ghost" onClick={()=>{setFrom('');setTo('');setQuery('')}}>Clear</button></div></Card>
 {view==='repairs'?<Card className="table-card"><table><thead><tr><th>Repair Date</th><th>Job / Customer</th><th>Device</th><th>Status</th><th>Repair Bill</th><th>Technician Earned</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.dbId}><td>{date(r.completedRaw||r.createdRaw)}</td><td><Link to={`/repairs/${r.id}`}><b>{r.id}</b></Link><small>{r.customer}</small></td><td>{r.phone}</td><td><Badge>{r.status}</Badge></td><td>{money(r.total)}</td><td><strong>{money(earningFor(r.dbId))}</strong>{!r.earningPosted&&<small>Not posted · awaiting full payment</small>}</td><td>{allowed&&r.earningPosted&&<button className="btn ghost sm" onClick={()=>open('adjust',selected,r)}>Adjust Earning</button>}</td></tr>)}{!rows.length&&<tr><td colSpan="7"><div className="empty-inline">No repairs match this date range or search.</div></td></tr>}</tbody></table></Card>:<Card className="table-card"><table><thead><tr><th>Date</th><th>Type</th><th>Repair</th><th>Note / Reference</th><th>Amount</th></tr></thead><tbody>{transactions.map(e=><tr key={e.id}><td>{date(e.created_at)}</td><td><Badge>{e.entry_type==='bonus'?'Manual Earning':e.entry_type==='deduction'?'Earning Reduction':e.entry_type==='payment'?'Settlement':e.entry_type}</Badge></td><td>{repairs.find(r=>r.dbId===e.repair_id)?.id||'Account'}</td><td>{e.description||'—'}</td><td className={signed(e)<0?'amount-negative':'amount-positive'}><strong>{signed(e)<0?'−':'+'}{money(Math.abs(signed(e)))}</strong></td></tr>)}{!transactions.length&&<tr><td colSpan="5"><div className="empty-inline">No ledger transactions match this filter.</div></td></tr>}</tbody></table></Card>}</>}
 {dialog&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={dialog.type==='settlement'?'Technician Settlement':dialog.type==='adjust'?'Adjust Repair Earning':'Add Manual Earning'}><Card className="modal-card ledger-modal"><div className="modal-header"><div className="modal-symbol"><WalletCards size={23}/></div><div><h2>{dialog.type==='settlement'?'Pay Technician':dialog.type==='adjust'?'Adjust Repair Earning':'Add Manual Earning'}</h2><p>{currentTech?.name}{dialog.repair?` · ${dialog.repair.id}`:''}</p></div><button className="iconbtn" aria-label="Close dialog" disabled={busy} onClick={()=>setDialog(null)}><X size={18}/></button></div><form onSubmit={save}><div className="balance-preview"><span>{dialog.type==='adjust'?'Current repair earning':'Current payable balance'}</span><strong>{money(dialog.type==='adjust'?earningFor(dialog.repair.dbId):currentTech?.balance)}</strong></div><label>{dialog.type==='settlement'?'Amount Paid (PKR)':dialog.type==='adjust'?'New Total Earning (PKR)':'Manual Earning Amount (PKR)'}<input autoFocus required type="number" step="0.01" min={dialog.type==='adjust'?0:0.01} max={dialog.type==='settlement'?currentTech?.balance:undefined} value={value} onChange={e=>setValue(e.target.value)}/></label>{dialog.type==='settlement'?<><label>Payment Method<select value={method} onChange={e=>setMethod(e.target.value)}><option>Cash</option><option>Bank Transfer</option><option>Easypaisa</option><option>JazzCash</option></select></label><div className="balance-preview remaining"><span>Balance After Payment</span><strong>{money(remaining)}</strong></div></>:<p className="field-help">{dialog.type==='adjust'?'Enter the final earning for this repair, not the difference. The adjustment changes the technician ledger; the customer bill stays the same.':'Adds an additional earning to this technician’s account with a permanent audit record.'}</p>}<label>{dialog.type==='settlement'?'Payment Reference / Note':'Adjustment Reason'}<textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder={dialog.type==='settlement'?'Weekly payment, transfer reference…':'Why is this earning being changed?'}/></label>{error&&<div className="form-error" role="alert">{error}</div>}<div className="split-actions"><button type="button" className="btn ghost" disabled={busy} onClick={()=>setDialog(null)}>Cancel</button><button className="btn primary" disabled={busy}>{busy?'Saving…':dialog.type==='settlement'?'Record Payment':dialog.type==='adjust'?'Save Earning':'Add Earning'}</button></div></form></Card></div>}</>
}
